# config.yaml
scenario: all   # all | base | budyko | budyko_da

paths:
  data_dir: data/processed
  result_dir: Simulation_results
  calibrated_params: SCE_cal_params/final_calibrated_params.json

# Data assimilation config
da:
  enabled: true
  nens: 10
  inflation: 0.5
  R_ET_std: 20.0
  proc_S_std: 0.13
  proc_G_std: 0.7
  P_std_frac: 0.10
  PET_std_frac: 0.03

parallel:
  enabled: true
  max_workers: -1

basins:
  subset: null

# Default run mode if CLI not provided
param_mode: Simulation_with_UNCALIB_PARAMS   # Simulation_with_CALIB_PARAMS | Simulation_with_UNCALIB_PARAMS

# Parameter configs (canonical keys!)
# params:
#   CALIBRATED:
#     use_calibrated: true

# #   UNCALIBRATED:
# #     use_calibrated: false
# #     random_seed: 1234

params:
  CALIBRATED:
    use_calibrated: true
  UNCALIBRATED:
    use_calibrated: false
    random_seed: 1234
    n_trials: 10      
    save_top_k: 5         
    bounds:
      Kperc: [0.1, 0.3]
      Kb: [0.01, 0.3]
      Ke: [0.1, 0.99]
      Cqq: [0.1, 0.90]
      Smax: [50, 800]
      Gmax_factor: [0.5, 20]
      fS0: [0.1, 0.9]
      fG0: [0.1, 0.8]


    # bounds:
    #   Kperc: [0.1, 0.4]
    #   Kb: [0.1, 0.4]
    #   Ke: [0.2, 0.5]
    #   Cqq: [0.1, 0.40]
    #   Smax: [50, 800]
    #   Gmax_factor: [0.5, 20]
    #   fS0: [0.1, 0.9]
    #   fG0: [0.1, 0.8]

# #
#     bounds:
#       Kperc: [0.01, 0.80]
#       Kb: [0.1, 0.80]
#       Ke: [0.1, 0.80]
#       Cqq: [0.1, 0.80]
#       Smax: [0.2, 2000.0]
#       Gmax_factor: [1.0, 1000.0]

#       fS0: [0.05, 0.95]
#       fG0: [0.05, 0.95]

