from __future__ import annotations
import os
import math
import numpy as np
import pandas as pd
import xarray as xr
import geopandas as gpd
import rioxarray
import fiona
import matplotlib.pyplot as plt
from shapely.geometry import Point, mapping
from dataclasses import dataclass, field
from typing import Tuple, Dict, List
from tqdm import tqdm
from scipy.optimize import minimize
from sklearn.metrics import mean_squared_error
from math import sqrt